language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t harshith12/react-test -f ./client/Dockerfile.dev ./client
    # add any other tests, if any

script:
        - docker run -e CI=true harshith12/react-test npm test

after_success:
    - docker build -t harshith12/multi-client ./client
    - docker build -t harshith12/multi-nginx ./nginx
    - docker build -t harshith12/multi-server ./server
    - docker build -t harshith12/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and send them to Docker Hub
    - docker push harshith12/multi-client
    - docker push harshith12/multi-nginx
    - docker push harshith12/multi-server
    - docker push harshith12/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-054373533536
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

